### ISSUE TITLE
Timeout not being respected

### ISSUE THREAD

**Issue by Sparticuz** [apaszke/tcp-ping#4]
Shouldn't this return false pretty much immediately? The timeout is 1ms. Instead it's waiting 21 seconds before returning false.
````
const tcp = require("tcp-ping");

let opts = {
    address: "good address",
    port: bad port,
    timeout: 1
}

tcp.ping({ address: opts.address, port: opts.port, attempts: 1, timeout: opts.timeout }, function(err, data) {
    let available = data.min !== undefined;
    console.log(available);
});
````

**Comment by apaszke** [comment]
It's possible that something has changed in the new Node versions I haven't been following that recently.

**Comment by Sparticuz** [comment]
Figured it out. I think it has something to do with me running it in the Ubuntu in Windows bash console. It seems to run properly on Linux proper.
